/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnimathclient_JNIMathClient */

#ifndef _Included_jnimathclient_JNIMathClient
#define _Included_jnimathclient_JNIMathClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnimathclient_JNIMathClient
 * Method:    addTwoNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jnimathclient_JNIMathClient_addTwoNumbers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnimathclient_JNIMathClient
 * Method:    multiplyTwoNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jnimathclient_JNIMathClient_multiplyTwoNumbers
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
